# Generated by Django 5.1.3 on 2025-04-21 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("salt", models.CharField(max_length=100)),
                ("iterations", models.IntegerField(default=100000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_changed", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.CharField(default="lock", max_length=50)),
                ("color", models.CharField(default="#007aff", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Password Categories",
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="PasswordEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("password", "Website Password"),
                            ("app", "App Password"),
                            ("wifi", "Wi-Fi Password"),
                            ("card", "Credit/Debit Card"),
                            ("note", "Secure Note"),
                            ("passkey", "Passkey"),
                            ("identity", "Identity"),
                        ],
                        default="password",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.BinaryField()),
                ("website_url", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weak", "Weak"),
                            ("medium", "Medium"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("password_iv", models.BinaryField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="password_management.passwordcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Password Entries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordCompromise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_date", models.DateTimeField(auto_now_add=True)),
                (
                    "breach_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "password_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="password_management.passwordentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_date", models.DateTimeField(auto_now_add=True)),
                ("access_type", models.CharField(max_length=20)),
                (
                    "device_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "password_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="password_management.passwordentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-access_date"],
            },
        ),
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credential_id", models.BinaryField()),
                ("public_key", models.BinaryField()),
                ("sign_count", models.BigIntegerField(default=0)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "password_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to="password_management.passwordentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_password", models.BinaryField()),
                ("changed_date", models.DateTimeField(auto_now_add=True)),
                ("password_iv", models.BinaryField()),
                (
                    "password_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="password_management.passwordentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Password Histories",
                "ordering": ["-changed_date"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_for_compromised", models.BooleanField(default=True)),
                ("suggest_strong_passwords", models.BooleanField(default=True)),
                ("min_password_length", models.IntegerField(default=12)),
                ("password_require_uppercase", models.BooleanField(default=True)),
                ("password_require_numbers", models.BooleanField(default=True)),
                ("password_require_symbols", models.BooleanField(default=True)),
                ("auto_fill_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
