# Generated by Django 5.1.3 on 2025-06-27 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the plan", max_length=100
                    ),
                ),
                (
                    "plan_code",
                    models.CharField(
                        help_text="Unique identifier for the plan (e.g., 'basic', 'premium')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Plan description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in INR",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "storage_gb",
                    models.IntegerField(
                        help_text="Storage limit in GB",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_sparkle",
                    models.BooleanField(
                        default=False,
                        help_text="Enable sparkle/premium features (false for basic plans)",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of features for this plan (JSON array)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for purchase",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30,
                        help_text="Plan validity in days",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="legacy_plan",
            field=models.CharField(
                blank=True,
                help_text="Legacy plan identifier (for migration)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid for this subscription",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                help_text="Selected subscription plan",
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.subscriptionplan",
            ),
        ),
    ]
