# Generated by Django 5.1.3 on 2025-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="assistant_settings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
