# Generated by Django 5.1.3 on 2025-04-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_management", "0009_userfile_is_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin Wallet",
                "verbose_name_plural": "Coin Wallets",
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("upload", "File Upload Reward"),
                            ("referral", "Referral Bonus"),
                            ("admin", "Admin Adjustment"),
                            ("redemption", "Coin Redemption"),
                            ("purchase", "Storage Purchase"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("running_balance", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "related_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file_management.userfile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="coin_wallet.coinwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin Transaction",
                "verbose_name_plural": "Coin Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
