# Generated by Django 5.1.3 on 2025-04-22 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistant", "0002_voiceinteraction_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceinteraction",
            name="conversation_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="voiceinteraction",
            name="reference_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
