# Generated by Django 5.1.3 on 2025-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistant", "0003_voiceinteraction_conversation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceinteraction",
            name="action_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="voiceinteraction",
            name="referenced_file_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voiceinteraction",
            name="referenced_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
