# Generated by Django 5.1.1 on 2024-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_ocrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
