# Generated by Django 5.1.3 on 2024-12-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_carddetails_appsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('document', 'Document'), ('card', 'Card'), ('subscription', 'Subscription')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('moved_to_expired', models.BooleanField(default=False)),
                ('original_category', models.CharField(blank=True, max_length=100)),
                ('expired_s3_key', models.CharField(blank=True, max_length=255)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_management.carddetails')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_management.userfile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_management.appsubscription')),
            ],
        ),
    ]
