# Generated by Django 5.1.3 on 2025-03-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0007_alter_userfile_options_userfile_file_size_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OCRPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("all", "Process OCR on all files"),
                            ("selected", "Process OCR only on selected files"),
                            ("none", "Do not process OCR on any files"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
