# Generated by Django 5.1.1 on 2025-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0008_alter_userfile_file_type_ocrpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
