# Generated by Django 5.1.3 on 2025-04-22 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0010_userfile_coins_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="pending_auto_categorization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="file_management.filecategory",
            ),
        ),
    ]
