# Generated by Django 5.1.3 on 2025-04-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0011_userfile_pending_auto_categorization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userfile",
            name="locked_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
