# Generated by Django 5.1.3 on 2025-05-24 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0013_userfile_document_pairing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="document_side",
            field=models.CharField(
                choices=[
                    ("single", "Single Side"),
                    ("front", "Front Side"),
                    ("back", "Back Side"),
                ],
                default="single",
                help_text="Indicates if this document has a front/back side",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="document_type_name",
            field=models.CharField(
                blank=True,
                help_text="Human readable document type (e.g., Aadhar Card, PAN Card)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="paired_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the other side of this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_with",
                to="file_management.userfile",
            ),
        ),
    ]
