# Generated by Django 5.1.3 on 2025-05-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0014_alter_userfile_document_side_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="document_side",
            field=models.CharField(
                choices=[
                    ("single", "Single Side"),
                    ("front", "Front Side"),
                    ("back", "Back Side"),
                ],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="document_type_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="paired_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_with",
                to="file_management.userfile",
            ),
        ),
    ]
