# Generated by Django 5.1.3 on 2025-06-27 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0015_alter_userfile_document_side_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="Hide file from normal view"
            ),
        ),
        migrations.AddField(
            model_name="userfile",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfile",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locked_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["user", "is_hidden"], name="file_manage_user_id_b28654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["user", "is_favorite"], name="file_manage_user_id_2f8860_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["user", "locked"], name="file_manage_user_id_fd796d_idx"
            ),
        ),
    ]
